# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=3.1.0
maven_group=com.totallynotsuspicious
archives_base_name=tns-core

# Dependencies
fabric_version=0.161.0+26.3
permissions_api_version=0.7.0
translation_api_version=3.2.0+26.3
placeholder_api_version=3.2.0+26.3
polymer_version=0.18.2+26.3
novoatlas_version=S3JujDfo
terralith_version=aGE3hYAA
lithostitched_version=FhKHD2LJ